### ISSUE TITLE
CoreOS nodes not connected on GCE

### ISSUE THREAD

**Issue by babarinde** [deis/deis#2940]
Hello and good day,
I av been battling with this for days now but am not sure where the issue lies here, whether its gce or the gce-user-data file or ME.
When trying to create the coreos nodes using the [docs](http://docs.deis.io/en/latest/installing_deis/gce/#launch-instances), the nodes are created, but when i ssh into one of the coreos nodes and i try 
```
fleetctl list-machines
```

It only returns the local IP of the current node and not the others as it should. This would obviously not allow deis to install the platfor later on.

Thanks

**Comment by babarinde** [comment]
Just tried creating new nodes on gce with a config
```
#cloud-config

coreos:
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    discovery: https://discovery.etcd.io/<token>
    # multi-region and multi-cloud deployments need to use $public_ipv4
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
```

ssh-ing into a node and fleetctl list-machines list all the nodes in the cluster
