### ISSUE TITLE
[Workflow] Unable to git push: Healthcheck error listing buckets

### ISSUE THREAD

**Issue by robinmonjo** [deis/deis#5085]
Hello,

I deployed Deis on an AWS multizone Kubernetes cluster. Trying to git push an app, the builder logs:

````
2016/08/19 16:32:41 Healthcheck error listing buckets (s3aws: NoSuchBucket: The specified bucket does not exist.
	status code: 404, request id: YDHA2ALY44G4WMX5)
````

Here is my deis builder config (`describe pods`)

````yaml
Name:		deis-builder-2602787563-viu9x
Namespace:	deis
Node:		ip-172-20-0-5.eu-west-1.compute.internal/172.20.0.5
Start Time:	Thu, 18 Aug 2016 18:03:01 +0200
Labels:		app=deis-builder
		pod-template-hash=2602787563
Status:		Running
IP:		10.244.0.9
Controllers:	ReplicaSet/deis-builder-2602787563
Containers:
  deis-builder:
    Container ID:	docker://0a113f324c84b70898e54ca980d2b1196dd53ca1f984fc7931201db2e41f9c4a
    Image:		quay.io/deis/builder:v2.3.0
    Image ID:		docker://sha256:a9393d8e3e52e64b83337c04f8e5fd1292fcac19219b1306548b2636ad681de5
    Ports:		2223/TCP, 8092/TCP
    State:		Running
      Started:		Thu, 18 Aug 2016 23:12:03 +0200
    Last State:		Terminated
      Reason:		Error
      Exit Code:	2
      Started:		Thu, 18 Aug 2016 23:10:51 +0200
      Finished:		Thu, 18 Aug 2016 23:11:21 +0200
    Ready:		True
    Restart Count:	6
    Liveness:		http-get http://:8092/healthz delay=30s timeout=1s period=10s #success=1 #failure=3
    Readiness:		http-get http://:8092/readiness delay=30s timeout=1s period=10s #success=1 #failure=3
    Environment Variables:
      DEIS_REGISTRY_SERVICE_HOST:	localhost
      DEIS_REGISTRY_SERVICE_PORT:	5555
      HEALTH_SERVER_PORT:		8092
      EXTERNAL_PORT:			2223
      BUILDER_STORAGE:			minio
      DEIS_REGISTRY_LOCATION:		on-cluster
      DEIS_REGISTRY_SECRET_PREFIX:	private-registry
      GIT_LOCK_TIMEOUT:			60
      SLUGBUILDER_IMAGE_NAME:		quay.io/deis/slugbuilder:v2.3.0
      DOCKERBUILDER_IMAGE_NAME:		quay.io/deis/dockerbuilder:v2.3.0
      DOCKERIMAGE:			1
      DEIS_DEBUG:			false
      POD_NAMESPACE:			deis (v1:metadata.namespace)
      DEIS_BUILDER_KEY:			<set to the key 'builder-key' in secret 'builder-key-auth'>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	True 
  PodScheduled 	True 
Volumes:
  builder-key-auth:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	builder-key-auth
  builder-ssh-private-keys:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	builder-ssh-private-keys
  objectstore-creds:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	objectstorage-keyfile
  deis-builder-token-zxwbb:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	deis-builder-token-zxwbb
QoS Tier:	BestEffort
Events:
  FirstSeen	LastSeen	Count	From							SubobjectPath			Type		Reason		Message
  ---------	--------	-----	----							-------------			--------	------		-------
  29m		3m		17	{kubelet ip-172-20-0-5.eu-west-1.compute.internal}	spec.containers{deis-builder}	Warning		Unhealthy	Liveness probe failed: HTTP probe failed with statuscode: 503
````

Any pointers on what could be wrong would be nice.
Regards,
Robin
